version: '3'

services:
  wordpress:
    build: .
    volumes:
      - ./:/usr/src/wordpress/wp-content/themes/janareznikova.cz
      - ../wp-plugins:/usr/src/wordpress/wp-content/plugins
      - ../wp-uploads:/usr/src/wordpress/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: example
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: example
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
